### ISSUE TITLE
Transpile to ES5

### ISSUE THREAD

**Issue by SebT** [SeregPie/VueWordCloud#12]
`VueWordCloud.js` uses ES2015+.

There should be a transpiled version of the file in ES6 using something like babel. (or it breaks most apps)

I can make a PR if you want.

EDIT: Actually, I can't get it working with rollup and babel as I don't have much exeperience with these tools and the file uses `Worker`.

**Comment by SeregPie** [comment]
Yes. This is really something, that needs to be done. I will look into this.

**Comment by SeregPie** [comment]
I think, there is nothing wrong to use a polyfill for `Worker`.

https://github.com/nolanlawson/pseudo-worker

``` html

<script src="https://unpkg.com/pseudo-worker/dist/pseudo-worker.polyfill.js"></script>

```

**Comment by SeregPie** [comment]
But as I wrote, this library is n a early stage. Everything can change. So it's better to wait a bit, before starting to think, how to translate the code to old ES.

**Comment by SebT** [comment]
The thing is I need my app to build for production with this lib pretty soon. I'll wait a few days before looking back into it but I think I'll have to get it working for myself. So I'll most likely make a PR when it's done. 

Transpiling to ES5 should have little impact on the source code, it will just add a `dist` or `lib` folder.

**Comment by SeregPie** [comment]
I never used babel before.

I separated the worker and the main code and wrote a small script to compile both files and then insert the content of one file into another.

This worked with the preset  `minify` but I had not luck with `es2015`. It compiles, but doesn't work.

=(

**Comment by SebT** [comment]
I think it's because of the header of the file (with `factory`, `exports`, ...).

My guess is that you should let the cbuild system handle that. Just use ES6 import/export. Take a look at: https://github.com/SebT/VueWordCloud/commit/4b04cf4c3314d64d1f2eb6af9c0b78ded11d44e6, this was my attempt a few days ago. Everything worked fine except I didn't handle workers.

It uses [rollup](https://rollupjs.org/).

**Comment by SebT** [comment]
I'm currently working on this with babel & rollup (see https://github.com/SebT/VueWordCloud/tree/build2). 

It's not working (at all) for now because the worker uses generator & async/await and for now I can't get babel to transpile the worker correcly. It compiles but fails at runtime.

I'll keep you up to date.

**Comment by SeregPie** [comment]
I also tried some things. Maybe this is even working. Do you have an old browser, like ie9? Can you test, if the file `VueWordCloud.es2015.min.js` is executing there?

**Comment by SebT** [comment]
Nice work ! VueWordCloud.es2015.min.js works ! \o/

To answer your question, it won't work on IE9: http://caniuse.com/#search=Web%20Worker. Support for web workers starts with IE 10, but others browsers support it for a while now ;)

A few notes:
- You should swap the names of the files `VueWordCloud.es2015.min.js` &  `VueWordCloud.min.js` because the one ending with es2015.min.js is actually ES5.
- You should add a build entry to generate the transpiled to ES5 filebut without minification (as most people have an uglify task in their build system already)

But a huge thanks for your work anyway !

**Comment by SeregPie** [comment]
Oh. I'm glad it is working. It was first time I used babel/rollup etc. And the workers made it really painful. I need to read more into watchers to automatize the process.
I will rename the files and add not minimized versions.
