### ISSUE TITLE
Words overlap a bit

### ISSUE THREAD

**Issue by SebT** [SeregPie/VueWordCloud#14]
Hello again,

I've noticed that words overlap a bit sometimes.

Here's a screenshot from your demo page:
![Screenshot](https://img11.hostingpics.net/pics/297723Screenshotfrom20171006114246.png)

**Comment by SeregPie** [comment]
Yes. I know. I also already know how to fix it. But first I need to impove the word-placing-algorithm to speed it up. I will do it soon.

**Comment by SeregPie** [comment]
Still not finished with the new algorithm but there must be much less text overlapping now.

**Comment by SeregPie** [comment]
#19

**Comment by SeregPie** [comment]
added some gaps between the words
