### ISSUE TITLE
Errors in npm versions

### ISSUE THREAD

**Issue by SebT** [SeregPie/VueWordCloud#15]
Hey,

I was using the file VueWordCloud.es2015.min.js from the commit c3b7f8dbdf584b34b9f6f251cbeddf42e415f9fc. Until now, it worked fine, the only issue was words overlapping a bit sometimes. 

You added a fix so I updated to version 17.10.15 (installed from npm) and I was using the file VueWordCloud.es5.min. It worked fine in dev mode, but when I builded my project (with wepack), I had runtime errors in the blob file `Uncaught (in promise) Error     at blob`. I know, this is not very explicit but it's all I had.

Then I tried the latest version from npm (17.10.18), with VueWordCloud.es5.js and it (kind of) works. I have Vue warnings: 
- `$attrs is readonly.` 
- `$listeners is readonly.` 
- `Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "words"`
- `Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "text"`
- `Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "weight"`
- `Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "rotation"`

and there is no more animations.

I downgraded to the first version mention in my post for now, awaiting a fix.

Any idea?

**Comment by SeregPie** [comment]
Sorry. Didn't tested much. I just needed fast a version with custom word renderer. I needed to drop animation for this. Just don't update for now. I will fix it.

**Comment by SebT** [comment]
Hi. Do you have an ETA on a fix for this and the animations ?

I'm supposed to deploy my app in a few days and I'm still using that old version :'(

**Comment by SeregPie** [comment]
no. not at the moment. have a lot to do with other stuff. i will come back to word cloud later.
=(
