### ISSUE TITLE
Doesn't work on iPad

### ISSUE THREAD

**Issue by SebT** [SeregPie/VueWordCloud#16]
Hello, it's me again ♪

I have the following errors:
- `TypeError: this.$el.getBoundingClientRect is not a function. (In 'this.$el.getBoundingClientRect()', 'this.$el.getBoundingClientRect' is undefined)` thrown by the method `updateContainerSize`
- `ReferenceError: Can't find private variable: @derivedConstructor` thrown my an anonymous function in `boundWords`

For your information, getBoundingClientRect compatibility: https://caniuse.com/#search=getBoundingClientRect

I think polyfilling it is the quickest way to fix this issue. Tell me if you can't work on it soon, I'll do a PR myself.

**Comment by SeregPie** [comment]
I could not find much about this issue on iPad. Anyway I rewrote the function. But I cannot test, if it fixed the issue.

**Comment by SebT** [comment]
Actually the `getBoundingClientRect` is supported on the iPad I used for the test. So I don't really know where the issue comes from.

For now I can't test either because I need the animations on the wordle so I can't update.

**Comment by SeregPie** [comment]
Check if you still have problems. I made a lot of changes lately.
