### ISSUE TITLE
Add space between words

### ISSUE THREAD

**Issue by tiagofscoelho** [SeregPie/VueWordCloud#19]
@SeregPie Is there any possibility to add a prop in order to add some space between each word? 

Some way to transform this:
![screen shot 2017-11-14 at 11 45 54](https://user-images.githubusercontent.com/7908689/32778604-793e7bba-c932-11e7-883d-e278980a89df.png)

Into this:
![screen shot 2017-11-14 at 11 53 15](https://user-images.githubusercontent.com/7908689/32778609-7c637a48-c932-11e7-9737-f8f38a1edb57.png)

Thanks in advance. 💯

**Comment by tiagofscoelho** [comment]
@SeregPie Can you give me some help here? I would like to provide a PR to this but I'll need some guide & input from your side to understand if this is possible and which steps should I made because the code is all about Math and doesn't have much code.

**Comment by SeregPie** [comment]
I'm already working on this Next version is on the way.

**Comment by SeregPie** [comment]
see #14
