### ISSUE TITLE
How can i use by cdn??

### ISSUE THREAD

**Issue by hskim1226** [SeregPie/VueWordCloud#20]
hi!

[this is my sample project](https://jsbin.com/dosahubaje/3/edit?html,css,js,console,output)
 but it is doesn't work
I  really wanna use it in my project.

If you reply, it help me a lot.

**Comment by SeregPie** [comment]
It has width and height `100%` by default. So it fills its container. Or you can set width and height by [yourself](https://jsbin.com/nuwiwaxoso/edit?html,css,js,console,output).
