### ISSUE TITLE
how can i use `animation-duration` ?

### ISSUE THREAD

**Issue by hskim1226** [SeregPie/VueWordCloud#21]
Thank you for quick response. One more question.
I really wanna use  `animation-duration`
[Like this example](https://jsbin.com/tipebihugo/edit?html,output)
[I try ](https://jsbin.com/hukigenega/edit?html,js,output)
but do not work.
how can i use `animation-duration` ?
My project can not use  `vuetify`

I look forward to your  reply.

**Comment by SeregPie** [comment]
There is no enter/leave animation yet, only change animation.
See [here](https://jsbin.com/basaperuji/edit?html,js,console,output).

**Comment by SeregPie** [comment]
The enter/leave animations are supported now.
