### ISSUE TITLE
Performance when rendering a lot of words

### ISSUE THREAD

**Issue by DRoet** [SeregPie/VueWordCloud#22]
Hi,

Great work so far with this library, I really like it.

However I have noticed some performance issues when trying to load +/- 200 words, the initial render feels a lot slower then something like: [wordcloud2.js](https://github.com/timdream/wordcloud2.js). I assume this is because of the rendering using `<div>` instead of `<canvas>`? From what I can tell there is also no callback function that tells me when the rendering is complete so it's difficult to display some sort of preloader in the meantime.

Any thoughts?

**Comment by SeregPie** [comment]
Hi.
I made a big update. How is performance now? Is it only slow in the demo? Try to turn off the animation.

**Comment by DRoet** [comment]
Hi,

I tested on the newest version (18.3.4) and turned off the animation, but unfortunately the issue still persists,

**Comment by SeregPie** [comment]
I plan to add an option to switch between dom and canvas renderer. Maybe it will help.

**Comment by SeregPie** [comment]
This one is pure canvas renderer.
https://seregpie.github.io/almete.WordCloud/
Check please how it performs by you.
