### ISSUE TITLE
(solved) word cloud did not show

### ISSUE THREAD

**Issue by maggiew61** [SeregPie/VueWordCloud#24]
I had trouble showing the word cloud graph. Then I figured out if I just added style="position:absolute" to the component then it would work. 
for example: 
<vue-word-cloud
**style="position:absolute"**
  :words="[['romance', 19], ['horror', 3], ['fantasy', 7], ['adventure', 3]]"
  :color="([, weight]) => weight > 10 ? 'DeepPink' : weight > 5 ? 'RoyalBlue' : 'Indigo'"
  font-family="Roboto"
></vue-word-cloud>

hope this will help some lost souls
btw thank you @SeregPie for this project

**Comment by SeregPie** [comment]
Oh. Can you please provide an example, where it does not work without `position: absolute`. It's strange, because the component is wrapped in a `div` with this style:
```js
position: 'relative',
width: '100%',
height: '100%',
overflow: 'hidden',
```

**Comment by maggiew61** [comment]
@SeregPie  thanks for the reply. sry about the late reply. I tried the code on both vue and codpen using cdn, and none of them worked unless I put the style="position:absolute" in inline tag. As for your question, frankly, I am not too familiar with positioning in css, so I don't know why, sorry about that. But nonetheless, besides this, everything worked fine and perfect

**Comment by dzeso** [comment]
it is an example of this problem. I can fix it by <v-card width="100%" height="100%"> --> <v-card width="100%" height="100vh">, but may you know some other way?

**Comment by dzeso** [comment]
Is there any way to have flexible height?

**Comment by SeregPie** [comment]
What do you mean? You can set percentage height.

**Comment by dzeso** [comment]
https://codepen.io/Dzeso/pen/eMbJrm - can you fix it in my example?

**Comment by SeregPie** [comment]
https://codepen.io/anon/pen/pLqeQM no problem.

**Comment by gadelkareem** [comment]
I think the problem with the style attr still exists

**Comment by wumoxi** [comment]
Oh, my god, it happened to me
