### ISSUE TITLE
[Feature request] Emit an event when render is done

### ISSUE THREAD

**Issue by tiagofscoelho** [SeregPie/VueWordCloud#25]
It is possible to emit an event when the render process is done? This way we can avoid an empty div (by showing a loading spinner or something else) while the render is being performed. 

Something like this would be great:

 ```
<vue-word-cloud @ready="SOME_FUNCTION"/>
```

**Comment by tiagofscoelho** [comment]
Any information regarding this feature request @SeregPie ?

**Comment by SeregPie** [comment]
Yes. I'm working on that in my free time.

**Comment by SeregPie** [comment]
You can watch the process with `process.sync`. I need to write it to readme, but meanwhile you can check the demo to see how it works.
