### ISSUE TITLE
[Feature request] Add an option to add space between each word on the cloud

### ISSUE THREAD

**Issue by tiagofscoelho** [SeregPie/VueWordCloud#26]
I am requesting this again because #14 didn't solve the problem of #19.
Is there a way to add a prop to define space between each word? Assuming that the prop will be called `space` (which is not a good name, just for an example), we could do something like

```
<vue-world-cloud :space="20"/>
```

This way each word will have a spacing between them of 20px at least.

**Comment by tiagofscoelho** [comment]
I am available to help you out with a PR if you give me some advice to tackle this issue since the code has a lot of math and not so many comment. 😄

**Comment by tiagofscoelho** [comment]
To give you a quick example of what I am trying to achieve, take a look at [the actual scenario](https://cl.ly/2P280p353g1T) and [the desired scenario](https://cl.ly/1O110B420O3P). Let me know if this is possible and If I can help you to do this.

**Comment by tiagofscoelho** [comment]
Any information regarding this feature request @SeregPie ?

**Comment by SeregPie** [comment]
Yes. I'm working on that in my free time. I'm testing it here.
https://seregpie.github.io/almete.WordCloud/

**Comment by SeregPie** [comment]
You can now change spacing between the words.
