### ISSUE TITLE
Animations doesn't work.

### ISSUE THREAD

**Issue by jesusvalle** [SeregPie/VueWordCloud#27]
Greetings.
I have tried many values for setting the animationDuration property, but it doesn't work. I've tried putting a rotation also, but at page load it only print's the words rotated without any animation transition too.

I need any dependency?
Thanks so much for your work.

`vue-word-cloud(:words="wordsCloud.words", :color="(wordsParams.color)", :fontFamily='wordsParams.fontFamily', :fontSizeRatio='wordsParams.fontSizeRatio' :animationDuration='1000')
`

**Comment by SeregPie** [comment]
Look at the minimal [example](https://jsbin.com/basaperuji/edit?html,js,console,output).
Does it not work for you?

**Comment by jesusvalle** [comment]
No, it doesn't, i've tested it to.

I only want the minimum enter animation, something like the example in your demo
https://seregpie.github.io/VueWordCloud/.

I'm using vue with typescript and pug, it could be a problem?

**Comment by SeregPie** [comment]
There is no enter or leave animation for now. Only change animation.

**Comment by jesusvalle** [comment]
Ok, thanks so much for your plugin and your time answering me.
