### ISSUE TITLE
word cloud did not show

### ISSUE THREAD

**Issue by lchhieu** [SeregPie/VueWordCloud#28]
I am trying use code demo but words don't seem is  show
```
<vue-word-cloud
                            :words="[['romance', 19], ['horror', 3], ['fantasy', 7], ['adventure', 3]]"
                            :color="([, weight]) => weight > 10 ? 'DeepPink' : weight > 5 ? 'RoyalBlue' : 'Indigo'"
                            font-family="Roboto"
                    ></vue-word-cloud>
```

result
`<div style="position: relative; width: 100%; height: 100%; overflow: hidden;"><div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);"></div></div>`

**Comment by SeregPie** [comment]
Without your code I cannot help you.

Try to set width and height of the word cloud.
```
style="width: 400px; height: 400px;"
```

**Comment by lchhieu** [comment]
I just update. Can you help me

**Comment by SeregPie** [comment]
Try to set width and height of the word cloud.
```
style="width: 400px; height: 400px;"
```

**Comment by lchhieu** [comment]
It worked well. thanks
