### ISSUE TITLE
[Bug Report] Chinese words are sticking together

### ISSUE THREAD

**Issue by francisfeng** [SeregPie/VueWordCloud#32]
Check out this jsfiddle: https://jsfiddle.net/eywraw8t/140773/ . 

These words are sticking together, making themselves barely recognizable. 

I think it will be great to provide an option with which each word takes up its own space without overlapping each other.

**Comment by SeregPie** [comment]
I think the problem is, that some lines are so small, so they are not even visible when calculating pixels with the help of the canvas.

You can try to add some spacing between the words with `:spacing="1/8"` for example.
https://jsfiddle.net/fhcmtkdw/

**Comment by SeregPie** [comment]
Which browser do you use? Which version? Which OS?

This is how it looks on my side.

![](https://i.imgur.com/9bfLUid.jpg)

**Comment by SeregPie** [comment]
How does it looks like if you insert your text into the demo?

https://seregpie.github.io/VueWordCloud/

```
北京 30
上海 26
广州 11
Shanghai 10
西安 3
深圳 2
Guangzhou 1
杭州"1
Nanjing 1
Changsha 1
成都 1
```

**Comment by francisfeng** [comment]
On Windows 1803, Chrome  67.0.3396.99 (the current latest Chrome).

It works fine on https://seregpie.github.io/VueWordCloud/

![image](https://user-images.githubusercontent.com/1040288/42376374-8b7b385e-8151-11e8-986d-c2db36af2963.png)

**Comment by SeregPie** [comment]
Hmm...
By you it is working in demo but does not work on jsfiddle.net.
By me it is working there and there.
I also have Chrome 67.

The only problem, I could think of, are the fonts.
Look if this throws errors for you.
https://jsfiddle.net/fhcmtkdw/17/
Maybe try to change the font family.

**Comment by francisfeng** [comment]
No, it didn't throw any errors.

Each time I changed the font, the rendered word cloud did looked different. But they were still overlapping each other.

-----
![image](https://user-images.githubusercontent.com/1040288/42388454-1d5c546c-8178-11e8-8481-1411d429b44e.png)
Mircosoft Yahei

-----

![image](https://user-images.githubusercontent.com/1040288/42388393-f7f22dd2-8177-11e8-83bb-42a54a554405.png)
[Noto Sans CJK SC](https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKsc-hinted.zip)
https://jsfiddle.net/fhcmtkdw/25/

-----

**Comment by avrinfly** [comment]
> 
Have you solved this problem?
