### ISSUE TITLE
Is this scenario implementable?

### ISSUE THREAD

**Issue by nicroto** [SeregPie/VueWordCloud#34]
So I still have the issue #33, but would like to know if my scenario is even doable with VWC.

Can I use this component to dynamically load and add content to the cloud on scroll? Or will it constantly recompute and remove any scrolling?

Thanks.

**Comment by SeregPie** [comment]
The cloud recomputes only if you change a property or the size of the cloud changes.

**Comment by nicroto** [comment]
The scenario basically comes down to whether this is supported - adding more items to the cloud, doesn't recompute the previously rendered content (not a pixel is moved from the previous rendered), but adds to it. Is this supported?

**Comment by SeregPie** [comment]
No. Its not supported... not right now. But it would be a good feature. Maybe I will implement it but not in the near future.

**Comment by nicroto** [comment]
Thanks for the reply.
