### ISSUE TITLE
Colours overridden by bootstrap when @media =  print

### ISSUE THREAD

**Issue by WebDevRock** [SeregPie/VueWordCloud#35]
Because Bootstrap is naughty and uses !important in the @print media setting the generated WordCloud styles are stripped if you print them.  
Would be good if you could use an inline !important to counteract that annoyance.

**Comment by SeregPie** [comment]
You can define slots. Look if it is working for you.
```html
<vue-word-cloud v-bind="myWordCloudOptions">
  <template slot-scope="{text, color}">
    <span :style="{color: `${color} !important`}">{{ text }}</span>
  </template>
</vue-word-cloud>
```
