### ISSUE TITLE
don't show component VueWordCloud

### ISSUE THREAD

**Issue by dmitryvasilevskiy** [SeregPie/VueWordCloud#37]
We included component, but it didn't show...

**Comment by SeregPie** [comment]
You need to set `width` and `height` on the parent element or on the `wordcloud` self.

**Comment by dmitryvasilevskiy** [comment]
`<template>
    <div style="width: 100%; height: 100%;">
        <vue-word-cloud
            :words="[['romance', 19], ['horror', 3], ['fantasy', 7], ['adventure', 3]]"
            :color="([, weight]) => weight > 10 ? 'DeepPink' : weight > 5 ? 'RoyalBlue' : 'Indigo'"
            font-family="Roboto"
        />
    </div>
</template>`

**Comment by dmitryvasilevskiy** [comment]
[It doesn't work.....](https://codeshare.io/amxABw)

**Comment by dmitryvasilevskiy** [comment]
[I can change it...](https://yadi.sk/i/dJyW6RhXzyaJbQ)

[This is example...](https://codeshare.io/amxABw)

**Comment by SeregPie** [comment]
not as property. as css style.
```
style="
  width: 640px;
  height: 480px;
"
```

**Comment by sudar** [comment]
@SeregPie 

Please add this to the Readme. Even I was not able to render the component after following the instructions in the readme.

After adding width & height it works now.
