### ISSUE TITLE
VueWordCloud do not show on firefox.

### ISSUE THREAD

**Issue by banbanmasa** [SeregPie/VueWordCloud#43]
I try to see VueWordCloud on firefox browser, but it's doesn't show.
On chrome I can see VueWordCloud.
My firefox version is 67.0.

**Comment by SeregPie** [comment]
But it works even in internet explorer.

**Comment by nwaughachukwuma** [comment]
It's not working for me yet @SeregPie

**Comment by sudar** [comment]
@banbanmasa @nwaughachukwuma 

You need to set the width & height. See #37

**Comment by nwaughachukwuma** [comment]
Thanks @sudar. That's exactly what I did

**Comment by SeregPie** [comment]
Updated the first example with set width and height styles.
