### ISSUE TITLE
  How to use in vue3

### ISSUE THREAD

**Issue by nintheaven** [SeregPie/VueWordCloud#53]

**Comment by brokelyn** [comment]
I tried to migrate it to Vue3 but yet no success (no more errors but nothing to see). But here are some tips for the migration:

- in the `render.js` one need to migrate the `$scopedSlots` like here [Vue3 Migration Docs - slots](https://v3.vuejs.org/guide/migration/slots-unification.html#_2-x-syntax)
- also in the `render.js` file the render function `h` now needs to be imported like here [Vue3 Migration Docs - render function](https://v3.vuejs.org/guide/migration/render-function-api.html#render-function-argument)

after that most of the errors are gone but neither of the two examples in the `README` produced an output for me. Maybe someone can do more research on this.

**Comment by rahulkumarsingh73690** [comment]
Any update on vue3?

**Comment by lovery** [comment]
@rahulkumarsingh73690 check out this [PR 56](https://github.com/SeregPie/VueWordCloud/pull/56)
I have an app based on vue3 and it works good.

**Comment by SeregPie** [comment]
Use v19.

**Comment by rahulkumarsingh73690** [comment]
Please provide demo how to use in vue 3 and nuxt 3

**Comment by Neil-Lin** [comment]
Nuxt 3
I create a file `useWordCloud.js` in composables
```javascript
import VueWordCloud from 'vuewordcloud'
export default function () {
  return {
    VueWordCloud
  }
}

```

 in .vue
```vue
<template>
  <div>
    <vue-word-cloud
      style="height: 480px; width: 640px"
      :words="[
        ['romance', 19],
        ['horror', 3],
        ['fantasy', 7],
        ['adventure', 3]
      ]"
      :color="([, weight]: [string, number]) => (weight > 10 ? 'DeepPink' : weight > 5 ? 'RoyalBlue' : 'Indigo')"
      font-family="Roboto"
    />
  </div>
</template>

<script setup lang="ts">
const { VueWordCloud } = useWordCloud()
</script>

```

It works for me.
